Hello

```{r}
library(tidyverse)
library(maps)
pollution<- read.csv('/Users/Gustavo/GitRStudio/pollution_2000_2023.csv')
```
Question: carbon monoxide in the country and pin point the cities with the highest and lowesr rates using maps(). 

```{r}
highest_City<- pollution %>%
  filter(year(Date)==2023)%>%
  group_by(City)%>%
  summarize(M_CO=mean(CO.AQI))%>%
  arrange(desc(M_CO))
head(highest_City,6)

low_City<- pollution %>%
  filter(year(Date)==2023)%>%
  group_by(City)%>%
  summarize(M_CO=mean(CO.AQI))%>%
  arrange((M_CO))
head(low_City,3)
```



Question: How has the average carbon monoxide (CO) level changed yearly in Phoenix?
Task: Filter the dataset for Phoenix and plot the yearly average of CO Mean values.
Air Quality Map by State

```{r}

Pol_city<-function(x){
  CO_plot<-data.frame(
   index=integer(),
   CO_M=numeric())

  PH<-pollution %>%
    filter(City %in% c(x))%>%
    arrange((Date))


  for (i in 2000:2023){
    PH_data<- PH %>%
      filter(year(Date)==i)
    CO_data<-c(mean(PH_data$CO.AQI,na.rm = TRUE))
    CO_plot <- rbind(CO_plot, data.frame(index = i, CO_M = CO_data))
  }


  
  
  ggplot (CO_plot,aes(x=index,y=CO_M))+
    geom_line(color='black',size=1)+
    geom_point(color='red',size=2)+
    labs(title=paste('Average Carbon Monoxide Air Quality Index in',x,'from 2000-2023'),
        x="Year", y= 'Carbon Monoxide')
}            
```


```{r}
Calexico_Pol<-Pol_city(c('Phoenix'))
Calexico_Pol

LA_Pol<-Pol_city(c('Los Angeles'))
LA_Pol

Lompoc_Pol<-Pol_city(c('Lompoc'))
Lompoc_Pol
```



```{r}
data("us.cities")
HI<-us.cities
LA<- us.cities%>%
  filter(name=='Los Angeles CA')
city_LA<- data.frame(x=LA$lat,y=LA$long)

LP<- us.cities%>%
  filter(name=='Lompoc CA')
city_LP<- data.frame(x=LP$lat,y=LP$long)

PH<- us.cities%>%
  filter(name=='Phoenix AZ')
city_PH<- data.frame(x=PH$lat,y=PH$long)

CH<- us.cities%>%
  filter(name== 'Cheyenne WY')
city_CH<- data.frame(x=CH$lat,y=CH$long)


map<-map_data('state')
ggplot()+
  geom_polygon(data=map,aes(x=long,y=lat,group=group),fill='white',color='black')+
  geom_point(data=city_LA,aes(x=y,y=x),color='red',size=3)+
  geom_point(data=city_LP,aes(x=y,y=x),color='darkgreen',size=5,shape=18)+
  geom_point(data=city_PH,aes(x=y,y=x),color='red',size=3)+
  geom_point(data=city_CH,aes(x=y,y=x),color='darkgreen',size=5,shape=18)+
  labs(title='Highest and Lowest location of Carbon Monoxide',x='Long',y='Lat')
```

