---
title: "SantanaLance_STAT107_Project"
author: "Lance Santana"
date: "November 16th, 2024"
format: html
editor: visual
---

## Quarto

## Running Code

Installs needed packages:

```{r}
#install packages
install.packages("ggplot2")
install.packages("maps")
install.packages("tidyverse")
```

Loads libraries:

```{r}
#Loading libraries
library(ggplot2)
library(maps)
library(tidyverse)
```

Reads and cleans pollution data set:

```{r}
#Read pollution.csv data set
pollution_data <- read.csv("/Users/lancesantana/Downloads/School Files/Active Files/STAT_107 Files/STAT_107_Git_Files/Stats107_Project/pollution_2000_2023.csv")

#Removes negative values from data (-1e-10 used because 0 returned values close to 0 i.e Kansas City	-0.000706)
pollution_data <- pollution_data[pollution_data$O3.Mean >= -1e-10,]
```

Question #1:\
Which cities have the highest recorded ozone pollution levels?

Which cities have the lowest recorded ozone pollution levels?

```{r}
#Sorts highest & lowest 100 ozone samples into a data frame
top_oz_samples <- pollution_data[order(pollution_data$O3.Mean, decreasing = TRUE),]
top_oz_cities <- top_oz_samples[1:100, c("State", "City", "O3.Mean")]
top_oz_cities

bottom_oz_samples <- pollution_data[order(pollution_data$O3.Mean, decreasing = FALSE),]
bottom_oz_cities <- bottom_oz_samples[1:100, c("State", "City", "O3.Mean")]
bottom_oz_cities
```

Question #1a:\
What are the most and least effected cities by ozone pollution?

```{r}
#Creates us.cities, needed for mapping, contains city coordinators
data("us.cities")
us_cities <- us.cities
us_cities$name <- sapply(strsplit(us_cities$name," "), function(x) x[1])

#Set variable with highest ozone city coordinators
oz_cities_match_top_100 <- us_cities %>%
  filter(name %in% top_100_oz_cities$City)

#Set variable with lowest ozone city coordinators
oz_cities_match_bottom_100 <- us_cities %>%
  filter(name %in% bottom_100_oz_cities$City)

#Maps cities 
maps ::map("state")
points(oz_cities_match_top_100$long, oz_cities_match_top_100$lat, col = "red", pch = 7)
points(oz_cities_match_bottom_100$long, oz_cities_match_bottom_100$lat, col = "blue", pch = 7)
legend("bottomright", legend = c("Highest Ozone", "Lowest Ozone"), col = c("red", "blue"), pch = c(7, 7), title = "Legend")
title(main = "Cities by Highest and Lowest Ozone Pollution")

#Potential Issues:
# 1. us.cities does not have all the cities listed in our data set
# 2. inaccurate sampling resulting in false 0 samples (evidenced by values less than 0)
# 3. data emphasis on highly populated areas
```

```{r}
#Finds state average ozone
avg_oz_states <- data.frame(State = unique(pollution_data$State), Mean_03 = NA)
for (i in 1:nrow(avg_oz_states)){
  state_name <- avg_oz_states$State[i]
  state_info <- pollution_data[pollution_data$State == state_name, ]
  avg_oz_states$Mean_O3[i] <- mean(state_info$O3.Mean)
}

#Sorts by highest mean ozone
avg_oz_states <- avg_oz_states[order(avg_oz_states$Mean_O3),]

#Selects and prints highest three states from data
top_3_oz_states <- avg_oz_states[1:3, c("State", "Mean_O3")]
top_3_oz_states

#Sorts by lowest mean ozone
avg_oz_states <- avg_oz_states[order(-avg_oz_states$Mean_O3),]

#Selects and prints highest three states from data
bottom_3_oz_states <- avg_oz_states[1:3, c("State", "Mean_O3")]
bottom_3_oz_states
```

```{r}
#Collects data for Tennessee
tenne_data <- pollution_data %>%
  filter(State == "Tennessee")

#Collects data for Alaska
alask_data <- pollution_data %>%
  filter(State == "Alaska")

#Collects data for California
cali_data <- pollution_data %>%
  filter(State == "California")

#Graphs box plot from Tennessee data
ggplot(tenne_data, aes(x = O3.Mean)) +
  geom_boxplot(fill = "red", color = "black") + 
  labs(title = "Tennessee", x = "Ozone Samples") +
  xlim(-.0006, 0.102) +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )

#Graphs box plot from Alaska data
ggplot(alask_data, aes(x = O3.Mean)) +
  geom_boxplot(fill = "blue", color = "black") +
  xlim(-.0006, 0.102) +
  labs(title = "Alaska", x = "Ozone Samples")  +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )

#Graphs box plot from California data
ggplot(cali_data, aes(x = O3.Mean)) +
  geom_boxplot(fill = "purple", color = "black") + 
  labs(title = "California", x = "Ozone Samples") +
  xlim(-.0006, 0.102) +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )
```

```{r}
#Calculate highest, lowest average state ozone and median average value
highest_ozone_state_value <- max(oz_mean_by_state$average_ozone_mean)
lowest_ozone_state_value <- min(oz_mean_by_state$average_ozone_mean)
median_ozone_state_value <- median(oz_mean_by_state$average_ozone_mean)

#Uses highest and lowest values to find highest and lowest states
higest_ozone_state <- oz_mean_by_state %>%
  filter(average_ozone_mean == highest_ozone_state_value)

lowest_ozone_state <- oz_mean_by_state %>%
  filter(average_ozone_mean == lowest_ozone_state_value)

#prints high / low states and median state ozone 
cat("State with highest average ozone level:\n", higest_ozone_state$State, higest_ozone_state$average_ozone_mean,"\n\n") 
cat("State with lowest average ozone level:\n", lowest_ozone_state$State, lowest_ozone_state$average_ozone_mean,"\n\n") 
cat("Median State Ozone:", median(oz_mean_by_state$average_ozone_mean),"\n\n")

#Comparison of California and Washington to previous data
print("California Average Ozone:")
mean(cali_data$O3.Mean)
cat("California's average ozone is ", higest_ozone_state$average_ozone_mean - mean(cali_data$O3.Mean), " below the highest state average\n")
cat("California's average ozone is ", mean(cali_data$O3.Mean) - median(oz_mean_by_state$average_ozone_mean), " above the median\n\n")
```

```{r}
#Preparing mean state ozone data by grouping and ordering
oz_mean_by_state <- pollution_data %>%
  group_by(State) %>%
  summarize(average_ozone_mean = mean(O3.Mean, na.rm = TRUE)) %>%
  arrange(desc(average_ozone_mean))

#Adding color to select states
oz_mean_by_state$fill_color <- "gray"
oz_mean_by_state$fill_color[oz_mean_by_state$State == "California"] <- "purple"
oz_mean_by_state$fill_color[oz_mean_by_state$State == "Tennessee"] <- "red"
oz_mean_by_state$fill_color[oz_mean_by_state$State == "Alaska"] <- "blue"

#Graphing all states average ozone with dashed median line
ggplot(oz_mean_by_state, aes(x = reorder(State, average_ozone_mean), y = average_ozone_mean)) +
  geom_bar(stat = "identity", fill = oz_mean_by_state$fill_color) +
  geom_hline(yintercept = median(oz_mean_by_state$average_ozone_mean), color = "purple", linetype = "dashed", linewidth = 1) +
  scale_fill_identity() +
  labs(title = "State Mean Ozone Levels", x = "State", y = "Average City Ozone") +
  theme(
    axis.text.x = element_blank()
  )
```

```{r}
#Creates us.cities, needed for maping, contains city coordinators
data("us.cities")
us_cities <- us.cities
us_cities$name <- sapply(strsplit(us_cities$name," "), function(x) x[1])

#set variable with highest ozone city coordinators
oz_cities_match_top <- us_cities %>%
  filter(name %in% top_3_oz_cities$City)

#set variable with lowest ozone city coordinators
oz_cities_match_bottom <- us_cities %>%
  filter(name %in% bottom_3_oz_cities$City)

#maps cities 
maps ::map("state")
points(oz_cities_match_top$long, oz_cities_match_top$lat, col = "red", pch = 7)
points(oz_cities_match_bottom$long, oz_cities_match_bottom$lat, col = "blue", pch = 7)
legend("bottomright", legend = c("Highest Ozone", "Lowest Ozone"), col = c("red", "blue"), pch = c(7, 7), title = "Legend")

#Potential Issues:
# 1. California is not on the list although it has notably the worst state by ozone pollution
```
