```{r}
library(tidyverse)
library (maps)
```

```{r}
pollution <-read.csv("C:\\Users\\Cole H\\Downloads\\pollution_2000_2023.csv\\pollution_2000_2023.csv")
pollution
```

```{r}
filtered_states <-pollution %>%
  filter(!State %in% c("Alaska", "Hawaii", "District Of Columbia"))
```

```{r}
  sulfur_5 <- filtered_states %>%
  group_by(State) %>%
  summarize(average_sulfur = mean(SO2.Mean, na.rm = TRUE)) %>%
  arrange(desc(average_sulfur))%>%
  head(5)

print(sulfur_5)



```

```{r}
us_states <- map_data("state") 
sulfur_5 <- sulfur_5 %>%
  mutate(state = tolower(State))  

sulfur_5_map <- us_states %>%
  inner_join(sulfur_5, by = c("region" = "state"))

ggplot() +
  geom_polygon(data = us_states, aes(x = long, y = lat, group = group),
               fill = "gray", color = "white") +  
  geom_polygon(data = sulfur_5_map, aes(x = long, y = lat, group = group, fill = average_sulfur),
               color = "white") +  
  scale_fill_gradient(low = "yellow", high = "red", name = "Avg Sulfur Level") +
  theme_minimal() +
  labs(title = "Top 5 States by Average Sulfur Levels", x = "Longitude", y = "Latitude")
```

```{r}
filtered_states$Date <- as.numeric(sub(".*/.*/", "", filtered_states$Date)) 
filtered_data <- subset(filtered_states, Date >= 2018 & Date <= 2023)

sulfur_5New <-filtered_data%>%
  group_by(State) %>%
  summarize(average_sulfur = mean(SO2.Mean, na.rm = TRUE)) %>%
  arrange(desc(average_sulfur))%>%
  head(5)
  
  print(sulfur_5New)
```

```{r}
us_states <- map_data("state") 
sulfur_5New <- sulfur_5New %>%
  mutate(state = tolower(State))  

sulfur_5New_map <- us_states %>%
  inner_join(sulfur_5New, by = c("region" = "state"))

ggplot() +
  geom_polygon(data = us_states, aes(x = long, y = lat, group = group),
               fill = "gray", color = "white") +  
  geom_polygon(data = sulfur_5New_map, aes(x = long, y = lat, group = group, fill = average_sulfur),
               color = "white") +  
  scale_fill_gradient(low = "yellow", high = "red", name = "Avg Sulfur Level") +
  theme_minimal() +
  labs(title = "Top 5 States by Average Sulfur Levels", x = "Longitude", y = "Latitude")
```

```{r}
top_5 <- c("New York", "Kentucky", "Pennsylvania", "Wisconsin", "Virginia")

top_cities <- pollution %>%
  filter(State %in% top_5) %>%           
  group_by(State, City) %>%                    
  summarize(city_sulf = mean(SO2.Mean),
            .groups = "drop") %>%
  arrange(State, desc(city_sulf)) %>%          
  group_by(State) %>%                          
  slice_max(city_sulf, n = 3) %>%             
  ungroup()                                   

print(top_cities)
```
